
title: GappsLite
email: GappsLite
description: "GappsLite"
baseurl: "/"
url: "gappslite.github.io"
twitter_username: gappslite
github_username:  gappslite
author: gappslite

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
